# Generated by Django 4.2.4 on 2023-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="id",
        ),
        migrations.AlterField(
            model_name="song",
            name="sequence_number",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
